domain: yusolpark.github.io/M3/       
url: https://yusolpark.github.io/M3/ 
baseurl: /M3/  
remote_theme: chrisrhymes/bulma-clean-theme

title: M3 
description: "Welcome to the Modular Mouse Maze"


